---
title: "Sequencing_Based"
author: "Mikias HW"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---
# Prep Workspace
## Load libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)  # Data manipulation and visualization

library(Seurat)  # Single-cell RNA sequencing

library(SeuratData)

library(patchwork)  # Combine plots

library(conflicted)  # Resolve function name conflicts

```

## Conflicted functions
```{r results='hide', message=FALSE, warning=FALSE}
# Set function preferences
conflicts_prefer(dplyr::select)

conflicts_prefer(dplyr::filter)
```

## Define Directories
```{r}
# Project name
projectName <- "sequencing"

# Define and/or create data directory
dataDir <- paste(getwd(), "data", projectName, sep = "/")
dir.create(dataDir, recursive = TRUE)

# Check for datafiles
list.files(dataDir)

# Define and/or create output directory
outDir <- file.path(getwd(), "output", projectName, sep = "/")
dir.create(outDir, recursive = TRUE)
```

# Load data
```{r}
# InstallData("stxBrain")

brain <- LoadData("stxBrain", type = "anterior1")
```

# Preprocessing
```{r fig.width=16, fig.height=10}
plot1 <- VlnPlot(brain, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()

plot2 <- SpatialFeaturePlot(brain, features = "nCount_Spatial") + theme(legend.position = "right")

wrap_plots(plot1, plot2)
```

# Normalize
sctransform normalizes data, detects high-variance features & stores results in SCT assay
```{r}
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
```

# Visualize 
```{r fig.width=16, fig.height=10}
SpatialFeaturePlot(brain, features = c("Hpca", "Ttr"))
```

# Dim Down & View
```{r fig.width=16, fig.height=10}
# Quick workflow
brain <- brain |> 
  RunPCA(assay = "SCT", verbose = FALSE) |> 
  FindNeighbors(reduction = "pca", dims = 1:30) |> 
  FindClusters(verbose = FALSE) |> 
  RunUMAP(reduction = "pca", dims = 1:30)

# Side by side UMAP & Spatial
p1 <- DimPlot(brain, reduction = "umap", label = TRUE, label.size = 6)

p2 <- SpatialDimPlot(brain, label = TRUE, label.size = 6)

p1 + p2

# View specific clusters
SpatialDimPlot(brain, cells.highlight = CellsByIdentities(object = brain, idents = c(2, 1, 4, 3,
    5, 8)), facet.highlight = TRUE, ncol = 3)
```

# Interactive view
```{r eval=FALSE}
SpatialDimPlot(brain, interactive = TRUE)

LinkedDimPlot(brain)
```



